name: Expo actions
on:
  push:
    branches:
      - main
jobs:
  ValidateActor:
    runs-on: ubuntu-latest
    outputs:
      ACTOR: ${{ steps.actor.outputs.ACTOR }}
    steps:
      - id: actor
        run: |
          if [[ ${{ github.actor }} != *"[bot]" ]];then
              echo "::set-output name=ACTOR::true" 
          else
              echo "::set-output name=ACTOR::false" 
          fi
  GenerateNewBuild:
    name: Build new artifact
    runs-on: ubuntu-latest
    needs: Publish_Updates
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          eas-cache: true
          token: ${{ secrets.EXPO_TOKEN }}
      - run: npm install
      - run: eas build -p android --profile production --non-interactive
