name: "Validate build and publish preview"

on:
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 🏗 Setup repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 9
          run_install: false
      - name: 🏗 Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: pnpm

      - name: 🏗 Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: 📦 Install dependencies
        run: pnpm install

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto